regulaforensics/FaceSDK-web-openapi

- comparison.yml
- remove 'format' property from CompareImage definition
> rl-452/format Format:

- comparison.yml
- detect.yml
- index.yml
> rl-440/detect Detect:

- common.yml
- index.yml
- liveness.yml
- add liveness endpoints open api definition without components descriptions
> rl-90/liveness Liveness:

- comparison.yml
- detect.yml
- liveness.yml
- add required properties
- rename integer types: number -> integer
> rl-468/cleanup Cleanup:

- common.yml
- comparison.yml
- detect.yml
- add FaceRecognitionResult definition
> rl-477/face-recognition-result FaceRecognitionResult:

- comparison.yml
- detect.yml
@ivan-gil 
@DmitrySmolyakov 
fyi
> clarify compare request

- matching.yml
- search.yml
https://app.clickup.com/t/4535044/SP-5228
> /api/search: Fixed similarity distance

- common.yml
- index.yml
- liveness.yml
**/api/v2/liveness/video [GET] -> application/octet-stream {binary}
/api/v2/liveness/portrait [GET] -> application/octet-stream {binary}**
> [SP-7406] Add video & portrait  for liveness v2

- matching.yml
https://app.clickup.com/t/4535044/SP-7680
> Added Ghost ImageSource enum type

- common.yml
- detect.yml
- index.yml
- liveness.yml
https://app.clickup.com/t/4535044/SP-7938
> Structure fix

- liveness.yml
https://app.clickup.com/t/4535044/SP-9037
> Liveness fix

- common.yml
- matching.yml
https://app.clickup.com/t/4535044/SP-7938
> Fixed Match (Comparison)

- identification.yml
- liveness.yml
- match_and_search.yml
- search.yml
https://app.clickup.com/t/4535044/SP-8722
> added descriptions to "tag", replaced SessionId

- detect.yml
- search.yml
https://app.clickup.com/t/4535044/SP-10295
> [SP-10561] Add search detection

- Makefile
- README.md
- common.yml
- detect.yml
- diagnostics.yml
- identification.yml
- index.yml
- liveness.yml
- match_and_search.yml
- matching.yml
- search.yml
https://app.clickup.com/t/4535044/SP-9984
> Release 5 2

- identification.yml
- liveness.yml
https://app.clickup.com/t/4535044/SP-10694
> Removed S3

- matching.yml
Reverts regulaforensics/FaceSDK-web-openapi#66
> Revert "SP-11596: Add outputImageParams"

- identification.yml
https://app.clickup.com/t/4535044/SP-11807
> SP-11807: Change image_id data type from int to str

- detect.yml
https://app.clickup.com/t/4535044/SP-12266
> Fix detect.yml

- common.yml
дополнение к https://github.com/regulaforensics/FaceSDK-web-openapi/pull/77
> Updated attributes description

- common.yml
Ticket: https://app.clickup.com/t/4535044/SP-12910
> SP-12910: Change class name for quality config

- common.yml
- detect.yml
- index.yml
- matching.yml
https://app.clickup.com/t/4535044/SP-11595
> Release 5.3

- .github/workflows/validate-spec.yml
- identification.yml
https://app.clickup.com/t/4535044/SP-13358
> SP-13358: Remove tag from person

- README.md
https://app.clickup.com/t/4535044/SP-12577
> Add link GitHub 12577

- index.yml
- liveness.yml
https://app.clickup.com/t/4535044/SP-12951 
https://app.clickup.com/t/4535044/SP-12577
> Fixed descriptions and index

- common.yml
https://app.clickup.com/t/4535044/SP-13356
> SP-13356: Change attributes' config schema

- match_and_search.yml
https://app.clickup.com/t/4535044/SP-13627
> SP-13627: Remove createPerson from math_and_search endpoint

- common.yml
- detect.yml
- identification.yml
- index.yml
- liveness.yml
- match_and_search.yml
- matching.yml
- search.yml
https://app.clickup.com/t/4535044/SP-7938
new enum members: FaceSDKResultCode, ImageSource
> Added descriptions, enum members

- common.yml
- detect.yml
- index.yml
- matching.yml
https://github.com/regulaforensics/FaceSDK-web-openapi/pull/91/files
> Fixes according to review

- identification.yml
- index.yml
- liveness.yml
- search.yml
https://app.clickup.com/t/4535044/SP-15040
> [Release 6.1]

- healthcheck.yml
https://app.clickup.com/t/4535044/SP-19382?comment=90120084727196
> Added descriptions /api/healthz & /api/readyz endpoints

- search.yml
https://app.clickup.com/t/4535044/SP-21294
> [SP-21294] Add 'withImages' query parameter to search
